 
name: Auto Merge Pull Requests

on:
  pull_request:
    types: 
      - opened
      - synchronize
      - labeled

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge pull request if conditions are met
        uses: "pascalgn/automerge-action@v0.15.4"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: "merge" # Options: merge, squash, rebase

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
